# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  gh: circleci/github-cli@2.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  fetch-nvrf:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    environment:
      URL: https://www.eac.gov/sites/default/files/eac_assets/1/6/Federal_Voter_Registration_ENG.pdf
    steps:
      #download pdf from
      - run: |
         curl -o Federal_Voter_Registration_ENG.pdf $URL
      #save pdf as an artifact
      - store_artifacts:
          path: Federal_Voter_Registration_ENG.pdf
          destination: /pdf-files
  create-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - gh/setup
      - run:
          name: Create Pull Request
          command: |
            gh auth login --token ${NVRF_PDF_WRITE}

        # gh branch create feature/updated-nvrf --from=stage
        # gh repo update --pull --base=stage --head=feature/updated-nvrf ${GITHUB_REPO}


        #  curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | DESTDIR=/usr/bin sudo bash
        #  circleci config upload -- repo ${GITHUB_REPO} -- branch feature/VOTE-289/download-nvrf-circleci -- file /pdf-files/Federal_Voter_Registration_ENG.pdf
        #  circleci create-pull-request -- repo ${GITHUB_REPO} -- branch feature/VOTE-289/download-nvrf-circleci -- title "New NVRF PDF" -- description "Replace the current NVRF PDF file with this file pulled from eac.gov"
    # IDEA: if the new pdf is the same as the old PDF, automatically merge PR

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  update-nvrf-workflow:
    jobs:
      - fetch-nvrf
      - create-pr:
          requires:
            - fetch-nvrf
