version: 2.1
orbs:
  gh: circleci/github-cli@2.2.0
jobs:
  cypress-testing:
    docker:
      - image: cypress/included:cypress-13.16.0-node-22.12.0-chrome-131.0.6778.108-1-ff-133.0-edge-131.0.2903.70-1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            cd testing
            npm install
      - run:
          name: Frontend Testing
          command: |
            npm start &
            cd testing
            npm run cy:test
      - run:
          name: Axe Testing
          command: |
            npm start &
            cd testing
            npm run cy:axe
workflows:
  main-workflow:
    jobs:
      - cypress-testing
